server:
  port: 8999

# database setting
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpastudy
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  ### Spring JPA 관련 셋팅 ###
  jpa:
    # database-platform : sql 구문을 날릴 때 뜽에 어떤 DB 언어를 기준으로 작성해야 될 것인지 갈피를 잡게 해 줌
    #                       - org.hibernate는 Spring Data JPA 를 사용하면 기본적으로 딸려 오는 패키지임
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    # Hibernate : ORM(Object-Relationap Mapping) 프레임 워크
    hibernate:
      # ddl
      #  - create : 매번 테이블 drop 후 재생성
      #  - update : alter table if exists tbl_product
      #  - none : 아무것도 못함
      ddl-auto: none
    properties:
      hibernate:
        # format_sql : SQL 로그 찍힐 때, 줄 맞춰서 이쁘게 나오게
        format_sql: true # SQL log
    # 위에 database-platform 설정해줬으므로 생략해줘도 되긴 함
    database: mysql

# log level setting
logging:
  level:
    root: info
    com:
      spring:
        jpastudy: debug
    org:
      hibernate:
        SQL: debug





